spring.application.name=PruebaTecnica
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pruebatecnica}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:miguel2}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
#PEGARLAS EN CRUDO A LAS URL, ANTES DE QIUE HAGA EL COMMIT
spring.jpa.properties.hibernate.format_sql=true
aes.secret.key=12345678901234567890123456789012
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs